name: Publish

on:
  workflow_call:
     inputs:
       version_type:
         required: true
         type: string
     secrets:
       npm_token:
         required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Grant NPM Private Package Access
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{secrets.npm_token}}

      - name: Install dependencies
        run: |
          yarn config set npmScopes.gasbuddy.npmRegistryServer "https://registry.npmjs.org"
          yarn config set npmScopes.gasbuddy.npmAlwaysAuth true
          yarn config set npmScopes.gasbuddy.npmAuthToken $NPM_TOKEN
          yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Publish
        run: npm publish . --tag ${{ inputs.version_type }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
